export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCESS = 'ORDER_CREATE_SUCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCESS = 'ORDER_DETAILS_SUCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
